### PR TITLE
Molex KK-6410 series: added 15 FreeCad models

### PR DESCRIPTION
**Pull request by hackscribble**
See main PR: https://github.com/KiCad/kicad-library/pull/1165

### CODE REVIEW

**Comment by hackscribble** [comment]
These models were generated from CadQuery scripts based on ones in https://github.com/easyw/kicad-3d-models-in-freecad

I will upload my versions to that repo, but should I also include them in this PR?

**Comment by poeschlr** [comment]
I think the freecad files for script generated models should not be added to this repo. Just add the information to the credits file and make a pull request to the repo by @easyw (Similar to the capacitors smd directory.)

@SchrodingersGat what do you think?

**Comment by easyw** [comment]
@hackscribble @poeschlr 
I don't think FC file needs to be added here.. the FC file in fact is just a solid model that doen't add anythink to the STEP model, because the result in FC is a model script generated... what is needed when the model is generated by a script is the link to the script generator in the PR and in the CREDITS.md file...
from the README.md file here
https://github.com/KiCad/packages3D/blob/master/README.md
> In case the model is generated by scripts, the scripts should be linked to the PR stating sw and version used to run the scripts; when the model is manually created, the MCAD source file should be added to the PR as well as STEP file. 

Please feel free to add a PR for your scripts @ my repo
https://github.com/easyw/kicad-3d-models-in-freecad
Thx a lot
Maurice

**Comment by hackscribble** [comment]
Thanks @easyw 

I will submit a PR to your repo for the scripts.  Then I will update this PR with a link and version details, and also add the details to the CREDITS.md file.

**Pull request closed without merging**
