### PR TITLE
De 113 rs 20

### PR DESCRIPTION
**Pull request by Misca1234**
Here is the replacement for the old DE-113-RS-20 displays

I added all three types and their variants from display-elektronik
wich have the same size and form factor as the DE-113-RS-20

There are 3 main symbols and the rest are aliases to those
DE 113-MS-20/7,5
DE 114-RS-20/6,35
DE 170-RS-20/7,5

I only added the 3D model of the 6.35mm pin lenght varaints, 
if you want I can add all variants as well, including 3D models

kicad-library push branch is 
https://github.com/KiCad/kicad-library/pull/1454

pretty push branch is 
https://github.com/KiCad/Displays_7-Segment.pretty/pull/8

packages3D push branch is 
https://github.com/KiCad/packages3D-source/pull/28

packages3D-source push branch is 
https://github.com/KiCad/packages3D/pull/94

bild

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
New 3D models

bild

bild

**Comment by poeschlr** [comment]
There is a DE-113 and a DE113 file included here. I think the one with "-" should not be here.

**Comment by Misca1234** [comment]
It have been removed

**Comment by poeschlr** [comment]
Thanks

**Comment by Misca1234** [comment]
Thx

**Pull request merged**
