### PR TITLE
Added EA_T123A-I2C

### PR DESCRIPTION
**Pull request by Misca1234**
Replacement of DISPLAY EA7123-12C placed in kicad-library,
no foot print connected, 

I assume it is EA T123A-I2C
http://www.lcd-module.com/deu/pdf/doma/t123-i2c.pdf

EA T123W-I2C
Is an alias to EA T123A-I2C

kicad-library push branch is
https://github.com/KiCad/kicad-library/pull/1461

pretty push branch is
https://github.com/KiCad/Displays.pretty/pull/23

packages3D push branch is
https://github.com/KiCad/packages3D/pull/98

packages3D-source push branch is
https://github.com/KiCad/packages3D-source/pull/32

NOTE:
This up pimping might be a little to much, the whole model is somewhere 50 tiems bigger than other, the .step file alone is 10Mb, it is the pixel array that make the size
let me now if I should down pimp it down

bild

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
10Mb for a step file is quite large.
It might really be a good idea to reduce the detail here.

**Comment by Misca1234** [comment]
New 3D model name and look 

bild

**Comment by poeschlr** [comment]
Thanks

**Comment by Misca1234** [comment]
Thx

**Pull request merged**
