### PR TITLE
Pimped up the 3D model and removed HY1602E from Display.3dshapes

### PR DESCRIPTION
**Pull request by Misca1234**
The source code for HY1602E

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
As with your other pull request, please move the credits file to the packages3d repo. (It holds the information that the user can find the source files here. Does not help a lot if you add the credits file here then.)

**Comment by Misca1234** [comment]
Done

**Comment by poeschlr** [comment]
Thanks

**Comment by Misca1234** [comment]
No problem

**Pull request merged**
