### PR TITLE
Added RC1602A

### PR DESCRIPTION
**Pull request by Misca1234**
Pimped up RC1602A, both foot print and 3D model

See 
https://github.com/KiCad/Displays.pretty/pull/15

bild

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
It looks like this now 

bild

**Comment by Misca1234** [comment]
See 
https://github.com/KiCad/kicad-library/pull/1388

Why it changed

**Comment by poeschlr** [comment]
Thanks

**Comment by Misca1234** [comment]
Great thanks

**Pull request merged**
