### PR TITLE
renamed one switch and made 3 variations

### PR DESCRIPTION
**Pull request by Shackmeister**
https://github.com/KiCad/packages3D/pull/57
https://github.com/KiCad/kicad-library/pull/1265
switches png

### CODE REVIEW

**Comment by poeschlr** [comment]
Am i right in assuming that the footprints are added by [Buttons_Switches_THT#19](https://github.com/KiCad/Buttons_Switches_THT.pretty/pull/19)?

**Comment by Shackmeister** [comment]
Exactly

**Comment by Shackmeister** [comment]
@poeschlr can you please also merge this?

**Comment by poeschlr** [comment]
Thanks for your contributions

**Pull request merged**
