### PR TITLE
Added LCD-016N002L and WC1602A

### PR DESCRIPTION
**Pull request by Misca1234**
This push consist of two devices, the reason for this 
is that the old symbol "LCD12X2" had LCD-016N002L1" as an alias,
I could not just remvoe this alias becosue travis started to scan LCD12X2 (with errors)
so i had to "fix" LCD12X2 as well.
Which I discovered that LCD12X2 actuallay is actually WC1602A 

So I have 
Fixed LCD-016N002L1
Removed  LCD12X2
Added WC1602A

I have modified symbol, footprint, 3D models

LCD-016N002L1
http://www.vishay.com/docs/37299/37299.pdf

WC1602A
http://dl.btc.pl/kamami_wa/wc1602a0.pdf

bild

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
credits file is in the wrong repo

**Comment by Misca1234** [comment]
It have been removed now

**Comment by poeschlr** [comment]
The A and K pins are located wrong for the LCD-016N002L

**Comment by Misca1234** [comment]
Swapped A and K numbering

bild

**Comment by Misca1234** [comment]
I also noticed that the K and A numbering was wrong, I re open the foot print push here
https://github.com/KiCad/Displays.pretty/pull/18

**Comment by Misca1234** [comment]
bild

**Comment by poeschlr** [comment]
Thanks

**Comment by Misca1234** [comment]
Thanks

**Pull request merged**
