### PR TITLE
Added CA56-12

### PR DESCRIPTION
**Pull request by Misca1234**
Added 
CA56-12CGKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/CA56-12CGKWA(Ver.9A).pdf

CA56-12EWA
http://www.kingbrightusa.com/images/catalog/SPEC/CA56-12EWA.pdf

CA56-12SEKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/CA56-12SEKWA(Ver.7A).pdf

CA56-12SURKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/CA56-12SURKWA(Ver.8A).pdf

CA56-12SYKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/CA56-12SYKWA(Ver.6A).pdf

to
modules/packages3d/Displays.3dshapes

The existing Cx56-12 was a CA56-12EWA 

Removed
modules/packages3d/Displays_7-Segment.3dshapes/Cx56-12.fcstd
modules/packages3d/Displays_7-Segment.3dshapes/Cx56-12.wrl

kicad-libray
https://github.com/KiCad/kicad-library/pull/1413

Displays.pretty
https://github.com/KiCad/Displays.pretty/pull/22

packages3D
https://github.com/KiCad/packages3D/pull/85

packages3D-source
https://github.com/KiCad/packages3D-source/pull/22

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
Moved the CA56 7 segment display to Displays_7-Segment, on request from poeschlr
See https://github.com/KiCad/Displays_7-Segment.pretty/pull/5 for more information

**Comment by poeschlr** [comment]
You did not remove it from displays.3d shapes
the displays_7-segment directory is missing the ending .3dshapes

**Comment by Misca1234** [comment]
aha. ok. one sec

**Comment by Misca1234** [comment]
I forgot to push, here you go

**Comment by poeschlr** [comment]
Did you push the correct branch? This pull request has no new commit.

**Comment by Misca1234** [comment]
Yes, I pushed wrong one, give me a second

**Comment by Misca1234** [comment]
Here you go

**Comment by poeschlr** [comment]
You forgot to delete the file from the displays repo.

**Comment by Misca1234** [comment]
Now it is gone

**Comment by poeschlr** [comment]
Thanks for this great contribution.

**Comment by Misca1234** [comment]
Thx

**Pull request merged**
