### PR TITLE
adding incomplete freecad model for RGB 1210 LED

### PR DESCRIPTION
**Pull request by hyOzd**
As requested by @Shackmeister in [this PR](https://github.com/KiCad/LEDs.pretty/pull/23#issuecomment-317987135) for RGB 1210 footprint.

### CODE REVIEW

**Comment by Shackmeister** [comment]
@hyOzd it looks prett complete to me, is it only the alignment and export missing?

**Comment by hyOzd** [comment]
I thought it required scaling.

**Comment by Shackmeister** [comment]
that too, but thats no problem. the modeling it self is complete right?

**Comment by hyOzd** [comment]
Yes the model is complete.

**Comment by Shackmeister** [comment]
sounds good thank you for your contribution

**Comment by poeschlr** [comment]
@hyOzd The scaling is done during the export step. (Kicad stepup does it automatically.)

**Comment by hyOzd** [comment]
Ok, so freecad models are kept in mm. Thank you.

**Comment by poeschlr** [comment]
Freecad and step models are in mm. To have the step models compatible with the footprint in this case, the footprint needs to have 1:1 scaling. Because of this requirement we need to scale the wrl model it self.

**Comment by Shackmeister** [comment]
@hyOzd you are welcome to try it out with the Stepup export tool, otherwise Ill add the 3D model when the footprint is merged

**Pull request merged**
