### PR TITLE
Lg206 l

### PR DESCRIPTION
**Pull request by Misca1234**
LG1206L
Alias LG206D

http://kodenshi.co.jp/products/pdf/sensor/photointerrupter_ic/LG205L.pdf
http://kodenshi.co.jp/products/pdf/sensor/photointerrupter_ic/LG206D.pdf

kicad-libaray push
https://github.com/KiCad/kicad-library/pull/1545

Opto-Devices.pretty
https://github.com/KiCad/Opto-Devices.pretty/pull/14

packages3D
https://github.com/KiCad/packages3D/pull/120

packages3D-source
https://github.com/KiCad/packages3D-source/pull/44

bild

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
see comments for footprint!

**Comment by Misca1234** [comment]
bild

bild

**Comment by Misca1234** [comment]
Renamed into PhotoInterrupter_Kodenshi_

**Comment by Misca1234** [comment]
bild


bild

bild

**Comment by jkriege2** [comment]
Thanks,
JAN

**Comment by jkriege2** [comment]
uuups I was too quick ... please have a look at my comment for the footprint. I think the nibbles are mirrored ... When you changed that, could you open another PR for this one? Thanks,
JAN

**Comment by Misca1234** [comment]
Here is the new PR 
https://github.com/KiCad/packages3D-source/pull/47

**Pull request merged**
